version: '3'
services:
  web:
    build: ./server
    command: yarn run api_blog
    volumes: 
      - ./server:/usr/app
      - /usr/app/node_modules
    ports:
      - "4000:6000"
    environment:
      PORT: 6000
      